# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 23:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=255)),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_completed',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('skill_name',),
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('secondary_email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(upload_to='images/profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
